import { hexToRgba } from "@/components/travel/utils";

interface IntentStackProps {
  accent?: string;
}

const INTENT_TIERS = [
  {
    tier: "High-Intent Velocity",
    range: "Weight 8 – 10",
    description:
      "Signals generated by deliberate, friction-bearing interactions. High cognitive cost to produce; strong predictor of conversion proximity. HADE treats these as primary scoring drivers.",
    signals: [
      "Back-Navigation Velocity",
      "Price-Filter Interaction",
      "Cart Add / Remove Delta",
      "Search Query Refinement",
    ],
    accent: "#316BFF",
  },
  {
    tier: "Mid-Intent Signals",
    range: "Weight 5 – 7",
    description:
      "Semi-passive telemetry that accumulates during normal session flow. Intent is inferred from behavioral patterns rather than explicit actions; confidence is attenuated by session duration.",
    signals: [
      "Dwell Time on PDP",
      "Comparison Frequency (PDP hopping)",
      "Scroll Depth (category pages)",
      "Structured Query Expansion",
    ],
    accent: "#6366F1",
  },
  {
    tier: "Persistence Signals",
    range: "Weight 3 – 4",
    description:
      "Cross-session and ambient signals that establish behavioral baseline. Used to modulate scoring sensitivity rather than drive primary intent classification.",
    signals: [
      "Repeat Session Return",
      "Time-on-Site Aggregate",
      "Passive Hover Accumulation",
    ],
    accent: "#8B5CF6",
  },
];

const SIGNAL_TABLE = [
  {
    signal: "Back-Navigation Velocity",
    latency: "Real-time ≤ 50 ms",
    intentStrength: 10,
    component: "Segment event stream → HADE scorer",
    tier: "High",
  },
  {
    signal: "Cart Add / Remove Delta",
    latency: "Real-time ≤ 150 ms",
    intentStrength: 9,
    component: "RudderStack → middleware state",
    tier: "High",
  },
  {
    signal: "Price-Filter Interaction",
    latency: "Real-time ≤ 100 ms",
    intentStrength: 9,
    component: "RudderStack → Node.js middleware",
    tier: "High",
  },
  {
    signal: "Search Query Refinement",
    latency: "Near-real-time ≤ 400 ms",
    intentStrength: 8,
    component: "NLP tokenizer → intent extractor",
    tier: "High",
  },
  {
    signal: "Comparison Frequency (PDPs)",
    latency: "Near-real-time ≤ 300 ms",
    intentStrength: 7,
    component: "Session JSON → HADE scoring model",
    tier: "Mid",
  },
  {
    signal: "Dwell Time (PDP)",
    latency: "Near-real-time ≤ 500 ms",
    intentStrength: 7,
    component: "Client telemetry → session buffer",
    tier: "Mid",
  },
  {
    signal: "Scroll Depth (category)",
    latency: "Batch ≤ 2 s",
    intentStrength: 5,
    component: "Segment page event → aggregator",
    tier: "Mid",
  },
  {
    signal: "Repeat Session Return",
    latency: "Async ≤ 5 s",
    intentStrength: 4,
    component: "Session persistence → state store",
    tier: "Persistence",
  },
];

const SYSTEM_FLOW = [
  {
    index: "01",
    label: "Client Emission",
    detail:
      "Segment or RudderStack SDK fires a structured event payload on every qualifying interaction. Each event carries a session ID, event type, timestamp, and a normalized context object. Idempotency keys are injected at the SDK layer to prevent duplicate downstream scoring on network retry.",
  },
  {
    index: "02",
    label: "Stream Ingestion",
    detail:
      "Events are buffered and forwarded to the HADE middleware service over an authenticated HTTP/2 stream. The ingestion endpoint is stateless; session state is reconstructed downstream from the ordered event buffer, decoupling ingestion throughput from scoring latency.",
  },
  {
    index: "03",
    label: "Session Hydration & Scoring",
    detail:
      "The Node.js / Python middleware reconstructs the session JSON from the event buffer. The HADE scoring model normalizes each raw telemetry value to a 0–1 float and applies tier-weighted coefficients. The composite Intent Score is computed via weighted summation across all active signals within the rolling session window.",
  },
  {
    index: "04",
    label: "Edge Dispatch & State Persistence",
    detail:
      "The scored intent payload is written to an edge-cached key-value store (Vercel KV or Cloudflare KV). TTL is set to session duration. Next.js Edge Middleware reads this payload at request time — before SSR — enabling catalog re-ordering with zero client-side reflow and full Edge-Caching compatibility.",
  },
  {
    index: "05",
    label: "Payload Optimization & DOM Delivery",
    detail:
      "The re-ordered product array is field-projected to ≤ 4 KB before serialization. Only the fields required by the initial render are included; full product records are lazily hydrated post-paint. This ensures Time-to-First-Byte is not impacted by HADE's scoring overhead.",
  },
  {
    index: "06",
    label: "A/B Validation via LaunchDarkly",
    detail:
      "A LaunchDarkly feature flag gates the adaptive delivery path at the edge. Control cohort receives the default sort order; treatment cohort receives the HADE-scored array. Conversion lift, add-to-cart rate, and session depth are tracked at the session level for statistical significance before full rollout.",
  },
];

const TIER_COLORS: Record<string, string> = {
  High: "#316BFF",
  Mid: "#6366F1",
  Persistence: "#8B5CF6",
};

export default function IntentStack({ accent = "#316BFF" }: IntentStackProps) {
  return (
    <div
      className="rounded-xl p-6 md:p-8 mb-10"
      style={{
        background: hexToRgba(accent, 0.03),
        border: "1px solid rgba(11,13,18,0.08)",
      }}
    >
      {/* Header */}
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-ink/40 mb-2">
        Technical Infrastructure & Signal Stack
      </p>
      <p className="text-sm text-ink/55 leading-relaxed mb-8 max-w-2xl">
        A deployable specification of how HADE ingests behavioral telemetry, normalizes raw events into weighted Intent Scores, and delivers re-ordered product arrays at the edge — before initial DOM paint.
      </p>

      {/* Intent Stack Hierarchy */}
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-ink/30 mb-3">
        1 — Intent Stack Hierarchy
      </p>
      <div className="grid gap-3 sm:grid-cols-3 mb-8">
        {INTENT_TIERS.map(({ tier, range, description, signals, accent: tierAccent }) => (
          <div
            key={tier}
            className="rounded-lg p-4"
            style={{
              borderLeft: `3px solid ${hexToRgba(tierAccent, 0.5)}`,
              background: hexToRgba(tierAccent, 0.04),
            }}
          >
            <p
              className="text-[10px] font-black uppercase tracking-[0.15em] mb-0.5"
              style={{ color: hexToRgba(tierAccent, 0.9) }}
            >
              {tier}
            </p>
            <p
              className="text-[10px] font-semibold mb-2"
              style={{ color: hexToRgba(tierAccent, 0.5) }}
            >
              {range}
            </p>
            <p className="text-xs text-ink/55 leading-relaxed mb-3">{description}</p>
            <ul className="space-y-1">
              {signals.map((s) => (
                <li key={s} className="text-[11px] text-ink/45 flex items-center gap-1.5">
                  <span
                    className="inline-block w-1 h-1 rounded-full flex-shrink-0"
                    style={{ background: hexToRgba(tierAccent, 0.6) }}
                  />
                  {s}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* Signal Weighting Table */}
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-ink/30 mb-3">
        2 — Signal Weighting Matrix
      </p>
      <div className="overflow-x-auto mb-8">
        <table className="w-full min-w-[640px] border-collapse">
          <thead>
            <tr style={{ borderBottom: "1px solid rgba(11,13,18,0.08)" }}>
              {["Signal", "Latency", "Intent Strength", "Infrastructure Component"].map((col) => (
                <th
                  key={col}
                  className="text-left text-[10px] font-semibold uppercase tracking-[0.15em] text-ink/35 pb-2 pr-4"
                >
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {SIGNAL_TABLE.map(({ signal, latency, intentStrength, component, tier }) => {
              const tierColor = TIER_COLORS[tier] ?? accent;
              const isHighIntent = intentStrength >= 8;
              return (
                <tr
                  key={signal}
                  style={{ borderBottom: "1px solid rgba(11,13,18,0.04)" }}
                >
                  <td className="text-sm text-ink/70 py-2.5 pr-4 font-medium">{signal}</td>
                  <td className="py-2.5 pr-4 font-mono text-xs text-ink/50">{latency}</td>
                  <td className="py-2.5 pr-4">
                    <span
                      className="inline-block text-xs font-bold px-2 py-0.5 rounded-full tabular-nums"
                      style={
                        isHighIntent
                          ? {
                              background: hexToRgba(tierColor, 0.12),
                              color: hexToRgba(tierColor, 1),
                            }
                          : {
                              background: "rgba(11,13,18,0.05)",
                              color: "rgba(11,13,18,0.45)",
                            }
                      }
                    >
                      {intentStrength} / 10
                    </span>
                  </td>
                  <td className="py-2.5 font-mono text-xs text-ink/45">{component}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* System Flow */}
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-ink/30 mb-3">
        3 — System Flow
      </p>
      <div className="space-y-0">
        {SYSTEM_FLOW.map(({ index, label, detail }, i) => (
          <div key={index} className="flex gap-4">
            <div className="flex flex-col items-center">
              <div
                className="w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 text-[9px] font-black"
                style={{
                  background: hexToRgba(accent, 0.1),
                  color: hexToRgba(accent, 0.9),
                }}
              >
                {index}
              </div>
              {i < SYSTEM_FLOW.length - 1 && (
                <div
                  className="w-px flex-1 mt-1"
                  style={{ background: hexToRgba(accent, 0.15), minHeight: "24px" }}
                />
              )}
            </div>
            <div className="pb-5">
              <p className="text-sm font-semibold text-ink/80 leading-snug mb-1">{label}</p>
              <p className="text-xs text-ink/50 leading-relaxed">{detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
